### ISSUE TITLE
Monitor not functionnal

### ISSUE THREAD

**Issue by jmlaniel** [marc365/AMOS-Professional-365#3]
When using the AMOS folder on an emulated Amiga 500 (with WIn-UAE), the monitor does not load.
![Untitled](https://user-images.githubusercontent.com/72532684/109445926-aae1fd00-7a0e-11eb-86b0-4e79f1db446d.png)

**Comment by marc365** [comment]
SnoopDOS tells me APSystem/AMOSPro_Monitor_Resource.Abk is not found.

The file is available in the floppy distribution AMOSPro_System:APSystem/

I will update the repo at the next opportunity and then close this issue.

Thanks for reporting.
