### ISSUE TITLE
Windows-DesktopRecorder

### ISSUE THREAD

**Issue by ErwinMeulman** [marc365/AMOS-Professional-365#5]
REMOVED: support request for different project.

**Comment by marc365** [comment]
the tool is only active if you run the .exe, it cannot do anything after a restart. the only registry setting it makes is for filename and encoding type setting for convenience. it taps into WASAPI audio driver and does not change any volume or setting  - I use it pretty much all the time and I have not seen that behaviour so would assume you have something else doing that.

**Comment by marc365** [comment]
spam removed.
